#!/usr/bin/env bash
# Takes a subdomain and a domain and returns information about the subdomain

# Function to get and print subdomain information
get_subdomain_info() {
    local subdomain=$1
    local domain=$2
    local dig_output
    dig_output=$(dig +short "$subdomain.$domain" ANY)

    if [ -n "$dig_output" ]; then
        local record_type=$(echo "$dig_output" | awk '{print $4}' | head -n 1)
        local destination=$(echo "$dig_output" | awk '{print $5}' | head -n 1)
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "The subdomain $subdomain does not have any records."
    fi
}

# Main script logic
DOMAIN=$1
SUBDOMAIN=$2

SUBDOMAINS=("www" "lb-01" "web-01" "web-02")

if [ -z "$SUBDOMAIN" ]; then
    for sub in "${SUBDOMAINS[@]}"; do
        get_subdomain_info "$sub" "$DOMAIN"
    done
else
    get_subdomain_info "$SUBDOMAIN" "$DOMAIN"
fi

